Parade location in overview
GroepBAvans/project-moesland pull request #106
Opened 2023-05-25 09:32 UTC by BjornVanBruchem

# Description

**Testen:**
- Maak een aantal evenementen en optochten aan.
- Kijk in het totaaloverzicht.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2023-05-25 09:47 UTC, KevinVanH requested changes

2023-05-25 09:47 UTC, KevinVanH commented on management/src/pages/events/overview.js
> +                                                <td className="location">Long/lat: {event.longitude.toFixed(3)}; {event.latitude.toFixed(3)}, Radius: {event.radius}m</td>
Ik vind dit wel gevaarlijk omdat een event database-technisch niet persé een longitude en latitude hoeft te hebben, je kan hier dus een exception krijgen als je toFixed op null aan zou roepen. Ik zou het iets exception safer maken

2023-05-25 10:16 UTC, KevinVanH approved these changes

2023-05-27 16:50 UTC, xandermonk approved these changes

2023-05-27 16:50 UTC, merged