Ml 86 overview voting
GroepBAvans/project-moesland pull request #113
Opened 2023-06-04 10:13 UTC by Veaxx

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-06-04 10:56 UTC, BjornVanBruchem commented on backend/routes/index.js
> +router.use('/api/vote', requestLimiter, require('./api/vote'));
Request limit op deze API call zou ik niet doen, er kunnen namelijk heel veel mensen tegelijkertijd stemmen.

2023-06-04 10:57 UTC, BjornVanBruchem requested changes

2023-06-04 10:57 UTC, BjornVanBruchem commented on backend/routes/index.js
> +router.use('/api/vote', requestLimiter, require('./api/vote'));
Request limit op deze API call zou ik niet doen, er kunnen namelijk heel veel mensen tegelijkertijd stemmen.

2023-06-04 11:07 UTC, BjornVanBruchem approved these changes

2023-06-05 18:25 UTC, xandermonk approved these changes

2023-06-05 19:37 UTC, merged