Ml 58 client voting
GroepBAvans/project-moesland pull request #114
Opened 2023-06-04 21:36 UTC by GXZheng312

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-06-05 18:31 UTC, xandermonk commented on moesland-app/src/modules/voting/VotingCategoryList.jsx
> +        <ScrollView>
In plaats van `ScrollView` zou je hier `FlatList` kunnen gebruiken. FlatList rendered alleen hetgeen dat je op dat moment op het scherm ziet. Het moet van mij niet, maar als het een mogelijkheid is dat deze lijst erg lang wordt is het een goede optie om te overwegen.

2023-06-05 18:41 UTC, xandermonk requested changes

2023-06-05 18:41 UTC, xandermonk commented on moesland-app/src/services/infoStorage.jsx
> +    if(fetchId == null) {
```suggestion
    if(fetchId === null) {
```

2023-06-05 18:41 UTC, xandermonk commented on moesland-app/src/services/MoeslandApi.jsx
> +export const BackendFetch = async (path, method, callback, body = null) => {
niet echt een beschrijvende naam voor een functie

2023-06-05 18:41 UTC, xandermonk commented on moesland-app/src/modules/voting/VotingItems.jsx
> +
```suggestion
```

2023-06-05 18:41 UTC, xandermonk commented on backend/routes/api/event/index.js
Kan niet op de juiste plek een comment achterlaten, weet ook niet of het jouw code is, maar hier kun je net zo goed de eerste API call in een variabele opslaan en dan meegeven, in plaats van 2x de call te doen.

![image](https://github.com/GroepBAvans/project-moesland/assets/56588736/7ca92139-21f6-4129-a093-7c25da08a3ff)

2023-06-05 19:27 UTC, GXZheng312 commented on moesland-app/src/services/MoeslandApi.jsx
> +export const BackendFetch = async (path, method, callback, body = null) => {
het is een generieke functionaliteit voor een api call naar de backend, heb je andere naam ideeën?

2023-06-05 19:29 UTC, GXZheng312 commented on moesland-app/src/modules/voting/VotingCategoryList.jsx
> +        <ScrollView>
Ik had eerst FlatList maar dat brengde problemen dat er geen andere type list mag voorkomen in zijn child

2023-06-05 19:31 UTC, GXZheng312 commented on backend/routes/api/event/index.js
niet mijn code, alleen wat groen is in gitchanges maar ik neem het wel mee

2023-06-05 19:43 UTC, xandermonk commented on moesland-app/src/services/MoeslandApi.jsx
> +export const BackendFetch = async (path, method, callback, body = null) => {
Fair enough, als dit verder geen unieke aspecten heeft om de naam voor te gebruiken zou je het kunnen verwoorden naar iets zoals `fetchDataFromBackend`. in principe hetzelfde, maar het leest wat makkelijker voor iemand die de code niet kent.

2023-06-05 20:24 UTC, xandermonk approved these changes

2023-06-06 07:12 UTC, BjornVanBruchem requested changes
Voordat je iets anders doet, moet je weer ff develop mergen met jouw branch. Er zijn veel dingen teruggedraaid die niet horen.

2023-06-06 07:12 UTC, BjornVanBruchem commented on backend/repository/userImage.js
> +    return UserImage.find({ approvalStatus: 'declined' }).populate('image')
Haal dit terug naar de originele (dus 1 methode met query als parameter).

2023-06-06 07:12 UTC, BjornVanBruchem commented on backend/routes/api/userImage/index.js
> +    return res.status(200).json(await getAllUserImages());
Zie vorige comment: een query als parameter meegeven.

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/layout/navbar.js
> -            });
Waarom is dit weggehaald? Dit is om de route te limiteren tot super admin, moet er dus wel in zitten.

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/layout/navbar.js
> +                                    <a className="dropdown-item" href="#">Goedgekeurde foto's</a>
Dit hoort ook niet

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/pages/events/overview.js
> +        const isOnlyParades = onlyParades === true ? '?onlyParades=true' : '';
Query als parameter

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/pages/events/overview.js
> -                                            )}
Dit terughalen

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/pages/photoManagement/approvedPhotoManagement.js
Dit bestand moet er in blijven

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/pages/photoManagement/declinedPhotoManagement.js
> -        await fetch(process.env.REACT_APP_BACKEND_ROOT_URL + '/api/user-image?approvalStatus=declined', { method: 'GET', headers: headers })
Dit terughalen

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/pages/photoManagement/photoManagement.js
> -        await fetch(process.env.REACT_APP_BACKEND_ROOT_URL + '/api/user-image?approvalStatus=pending', { method: 'GET', headers: headers })
Terughalen

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/pages/photoManagement/photoManagement.js
Dit bestand moet als de oude versie blijven

2023-06-06 07:12 UTC, BjornVanBruchem commented on management/src/routing.js
Dit bestand moet als de oude versie blijven

2023-06-06 07:12 UTC, BjornVanBruchem commented on moesland-app/src/modules/PhotoContentView.jsx
Deze moet naar mapje 'views' ipv 'modules'

2023-06-06 07:12 UTC, BjornVanBruchem commented on moesland-app/src/routes/MediaView.jsx
Dit bestand moet als de oude versie blijven

2023-06-06 07:12 UTC, BjornVanBruchem commented on moesland-app/src/styles/CalendarStyles.js
Dit bestand moet als de oude versie blijven

2023-06-06 07:58 UTC, BjornVanBruchem approved these changes

2023-06-06 08:09 UTC, FedorTselishchev approved these changes

2023-06-07 07:27 UTC, BjornVanBruchem approved these changes

2023-06-07 08:18 UTC, xandermonk approved these changes

2023-06-07 08:23 UTC, merged