Ml 119/swagger documentation
GroepBAvans/project-moesland pull request #116
Opened 2023-06-05 23:59 UTC by KevinVanH

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-06-06 07:00 UTC, BjornVanBruchem requested changes

2023-06-06 08:52 UTC, KevinVanH commented on backend/routes/index.js
> +router.use('/api/user/get-list', authenticateTokenRole('SuperAdmin'), require('./api/user/getList'));
Toegevoged!

2023-06-06 11:37 UTC, BjornVanBruchem approved these changes

2023-06-06 16:07 UTC, GXZheng312 commented
![image](https://github.com/GroepBAvans/project-moesland/assets/19644599/021a6c5e-560d-45ff-a81a-777b9f24f31f)

2023-06-06 16:09 UTC, GXZheng312 commented
Misschien is het ook een goed idee om een pagina aan te maken op de management site om de Swagger documentatie te tonen.

2023-06-07 08:26 UTC, GXZheng312 approved these changes

2023-06-07 08:27 UTC, merged