Event management/create update delete
GroepBAvans/project-moesland pull request #48
Opened 2023-04-24 19:31 UTC by Veaxx

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-04-25 09:59 UTC, xandermonk requested changes

2023-04-25 09:59 UTC, xandermonk commented on backend/repository/event.js
> +        return await Event.findById(id)
I think using 
`return await Event.findOne({ _id: { $eq: id } })`
solves the CodeQL error

source: @BjornVanBruchem made this fix in #44

2023-04-25 09:59 UTC, xandermonk commented on backend/routes/api/event/delete.js
> +        res.status(500).send(`Could not delete event:` + err);
`err` should be checked for dangerous html symbols. 

look into using [escapeHtml](https://www.npmjs.com/package/escape-html)

so that it becomes something like

```
const errorMessage = escapeHtml(`Could not delete event: ${err}`);
res.status(500).send(errorMessage);
```

2023-04-25 09:59 UTC, xandermonk commented on backend/routes/api/event/update.js
> +        res.status(500).json(`Could not update event: ` + err);
```suggestion
        res.status(500).json(`Could not update event: ${err}`);
```

2023-04-25 10:02 UTC, KevinVanH approved these changes
Approved, maar wel even de feedback van Xander verwerken

2023-05-08 10:24 UTC, xandermonk approved these changes

2023-05-08 10:34 UTC, merged