#56 general improvements
GroepBAvans/project-moesland pull request #55
Opened 2023-05-09 07:43 UTC by BjornVanBruchem

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-05-09 08:09 UTC, FedorTselishchev approved these changes
man wat goed
![image](https://user-images.githubusercontent.com/58981863/237034897-93d8dec9-e359-4d9b-9593-c9bcab715b65.png)

2023-05-09 08:36 UTC, Veaxx commented
![image](https://user-images.githubusercontent.com/70652307/237041505-05c46138-e780-42fa-9035-876a2e118504.png)

Verander die felle groene kleur naar huiskleuren van moesland (volgens mij had twan die ook gevraagd)

2023-05-09 08:40 UTC, Veaxx commented
![image](https://user-images.githubusercontent.com/70652307/237042440-61a66e5b-ec57-4880-aee5-efde0dfbe1fd.png)

Verwijder de aanpassen en verwijder knop als de persoon niet is ingelogd als SuperAdmin. Sinds je deze aanpassingen niet kan doen

2023-05-09 08:42 UTC, Veaxx commented
![image](https://user-images.githubusercontent.com/70652307/237042934-98a9dce0-9800-4476-b8d8-e20624c08f58.png)

Pagination doet het niet (pagina 2 bevat dezelfde dingen als pagina 1 terwijl er aan de hand van de meerdere records in mijn db minimaal 2 pagina's zou moeten hebben)

2023-05-09 08:42 UTC, Veaxx commented
![image](https://user-images.githubusercontent.com/70652307/237043171-80860460-3ca9-4077-982a-3df6b707f780.png)


Hier ook de kleur aanpassen naar de huiskleur

2023-05-09 08:43 UTC, Veaxx requested changes
.

2023-05-10 11:31 UTC, Veaxx approved these changes

2023-05-10 11:35 UTC, merged