#5 user foto management
GroepBAvans/project-moesland pull request #65
Opened 2023-05-11 12:02 UTC by BjornVanBruchem

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-05-11 12:26 UTC, xandermonk requested changes

2023-05-11 12:26 UTC, xandermonk commented on management/src/pages/RejectedphotoManagement.js
> +        const index = images.findIndex(i => i.description === item.userImageId);
Waarom wordt hier de description vergeleken met de ID? Lijkt me niet de juiste aanpak.

2023-05-11 12:26 UTC, xandermonk commented on management/src/pages/photoManagement.js
> +                        originalAlt: i.image.name,
```suggestion
                        originalAlt: i.image?.name,
```

2023-05-11 12:26 UTC, xandermonk commented on management/src/pages/RejectedphotoManagement.js
> +        console.log()
```suggestion
```
dit kan weg

2023-05-11 12:26 UTC, xandermonk commented on management/src/pages/RejectedphotoManagement.js
> +                        thumbnailAlt: i.image.name,
```suggestion
                        thumbnailAlt: i.image?.name,
```
voor het geval image niet bestaat, voorkomt een runtime error

2023-05-11 12:26 UTC, xandermonk commented on management/src/pages/photoManagement.js
> +        console.log()
```suggestion
```
dit kan weg

2023-05-11 12:26 UTC, xandermonk commented on management/src/pages/photoManagement.js
> +        const index = images.findIndex(i => i.description === item.userImageId);
Waarom wordt hier de description vergeleken met de ID? Lijkt me niet de juiste aanpak.

2023-05-11 16:47 UTC, Veaxx approved these changes

2023-05-12 07:51 UTC, GXZheng312 approved these changes

2023-05-12 07:53 UTC, merged