Ml 106 participation system crud
GroepBAvans/project-moesland pull request #77
Opened 2023-05-21 03:47 UTC by GXZheng312

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-05-22 15:43 UTC, KevinVanH approved these changes

2023-05-22 16:00 UTC, KevinVanH requested changes
Ik heb nog even wat meer getest, en de zoekalkjes in het CREATE scherm lijken niet goed te werken

2023-05-22 17:39 UTC, Veaxx requested changes

2023-05-22 17:39 UTC, Veaxx commented on management/src/modules/participation/form.js
> +                    <CustomSelectSearch
Filter overzicht van optionele evenementen op alleen Optochten sinds je alleen een deelname kan doen voor een optocht.
Dit kan je filteren via  **event.isParade == true**

2023-05-22 17:39 UTC, Veaxx commented on management/src/modules/participation/form.js
> +                    <CustomSelectSearch
Twijfel daarnaast ook of het misschien slim is om ook een filter te leggen op Optochten die nog moeten komen. Dus waarvan de begindatum nog niet is gestart. Omdat het onlogisch lijkt om op optochten te kunnen deelnemen die al zijn geweest

2023-05-22 17:39 UTC, Veaxx commented on management/src/modules/participation/form.js
> +                    <label className="float-start">Category</label>
```suggestion
                    <label className="float-start">Categorie</label>
```

2023-05-22 17:39 UTC, Veaxx commented on management/src/modules/participation/overview.js
> +                            <th scope="col">deelname</th>
```suggestion
                            <th scope="col">Deelname</th>
```

2023-05-22 17:39 UTC, Veaxx commented on management/src/modules/participation/overview.js
> +                            <th scope="col">Category</th>
```suggestion
                            <th scope="col">Categorie</th>
```

2023-05-22 17:39 UTC, Veaxx commented on management/src/modules/participation/overview.js
> +                            <th scope="col">Event</th>
```suggestion
                            <th scope="col">Evenement</th>
```

2023-05-22 17:39 UTC, Veaxx commented on backend/routes/api/participation.js
>      return next(err);
Negeer waar de comment staat. Maar -> Check bij de add of het startnr niet al bestaat bij de optocht. Sinds een startnummer uniek moet zijn. (twee deelnemers kunnen geen nr 30 hebben als startnummer natuurlijk)

2023-05-22 19:46 UTC, GXZheng312 commented on management/src/modules/participation/form.js
> +                    <CustomSelectSearch
Ja ik had de isParade check door de hoofd gezien. Maar idd is zeker onlogisch als er deelnames geplaatst op geweeste optochten

2023-05-22 19:50 UTC, GXZheng312 commented on backend/routes/api/participation.js
>      return next(err);
Ja, goed gezien ben ik helemaal vergeten

2023-05-23 16:32 UTC, KevinVanH requested changes

2023-05-23 16:32 UTC, KevinVanH commented on management/src/pages/participation.js
> +                    <button className="btn btn-moesland" onClick={toggleAddModal}>Nieuwe Deelnames</button>
Nieuwe Deelname, zonder S

2023-05-23 19:39 UTC, merged