Ml 101 participation system
GroepBAvans/project-moesland pull request #81
Opened 2023-05-23 19:40 UTC by GXZheng312

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-05-23 19:52 UTC, BjornVanBruchem commented on management/src/modules/participation/form.js
> +                    <input className="form-control" placeholder="Naam" name="name" defaultValue={data ? data.name : ""}></input>
Minimum lengte misschien?

2023-05-23 19:55 UTC, GXZheng312 commented on management/src/modules/participation/form.js
> +                    <input className="form-control" placeholder="Naam" name="name" defaultValue={data ? data.name : ""}></input>
hoeveel?

2023-05-24 07:32 UTC, BjornVanBruchem commented on management/src/modules/participation/form.js
> +    const [categorieOptions, setcategorieOptions] = useState([]);
`categorie` --> `category`

2023-05-24 07:36 UTC, BjornVanBruchem commented on backend/models.js
> +require('./models/paradeParticipationCategory');
Dit werkt niet, moet `participationCategory` zijn

2023-05-24 07:39 UTC, BjornVanBruchem commented on management/src/modules/participation/form.js
> +                    <input className="form-control" placeholder="Naam" name="name" defaultValue={data ? data.name : ""}></input>
3 ofzoiets, voortaan ook ff via Discord reageren aangezien ik hier geen notif's van krijg

2023-05-24 07:42 UTC, BjornVanBruchem commented on backend/repository/participation.js
> +};
Wees consistent en haal de methods binnen de exports zoals bij andere repo's

2023-05-24 07:44 UTC, BjornVanBruchem commented on backend/routes/api/paradeParticipationCategory/delete.js
> +    const paradeParticipationCategory = await getParadeParticipationCategoryByName(_id);
ByName maar je gebruikt een ID ...??

2023-05-24 07:49 UTC, BjornVanBruchem commented on management/src/modules/participation/overview.js
> +    const [participationData, setparticipationData] = useState(undefined);
Hoofdletters ❤️

2023-05-24 07:51 UTC, BjornVanBruchem requested changes
Verander `paradeParticipationCategory` naar `participationCategory`.
En volgens mij moet `Deelnames`, `Deelnemers` zijn.
(Tipje: Doe `CTRL+K` `CTRL+F` in elk bestand 😃)

2023-05-24 11:50 UTC, FedorTselishchev approved these changes
Gij werkt, goed werk!

2023-05-24 12:01 UTC, BjornVanBruchem approved these changes

2023-05-24 12:02 UTC, merged